language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - mysql

addons:
  firefox: latest
  chrome: stable
  hosts:
    - db.dev.local
    - db.test.local
    - api.dev.local
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: master

notifications:
  email: false

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot  
  - sudo mysql -u root -proot -e 'CREATE DATABASE `test-db`;'
  - sudo mysql -u root -proot -e "CREATE USER 'test-user'@'localhost' IDENTIFIED BY 'test-password';"
  - sudo mysql -u root -proot -e "GRANT ALL ON *.* TO 'test-user' @'localhost' WITH GRANT OPTION;"
  - sudo mysql -u root -proot -e "FLUSH PRIVILEGES;"
  - sudo service mysql restart

script:
  - cd apps && mvn clean install -Dspring.profiles.active=dev && mvn cobertura:cobertura