dist: xenial
os: linux
language: java
jdk:
  - openjdk8

addons:
  hosts:
    - api.dev.local

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: master

notifications:
  email: false

script:
  - cd apps && mvn clean install -Dspring.profiles.active=dev && mvn cobertura:cobertura