version: "2.2"

services:
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_dev
    container_name: spring-boot-seed-dev
    hostname: api.dev.local
    depends_on:
      - db
    image: spring-boot-seed/dev
    volumes:
      - ./api:/home/spring-boot-seed/api
    networks:
      - dev-network
    ports:
      - ${API_PORT}:8080
      - 10001:10001
    mem_limit: 768m
    cpu_percent: 60

  db:
    image: mysql:5.7.25
    container_name: spring-boot-seed-db-dev
    hostname: db.dev.local
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dev-db
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-password
    volumes:
      - ./mysql-dev/db:/var/lib/mysql
      - ./mysql-dev/dmp:/var/lib/mydmp
      - ./mysql-dev/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    networks:
      - dev-network

networks:
  dev-network:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK}
