version: "2.2"

services:
  db:
    image: mysql:5.7.25
    container_name: spring-boot-seed-db-test
    hostname: db.test.local
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test-db
      - MYSQL_USER=test-user
      - MYSQL_PASSWORD=test-password
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/dmp:/var/lib/mydmp
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    networks:
      - test-network

networks:
  test-network:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK}
