version: "2.2"

services:
  auth:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_auth_dev
    container_name: solicitudes-mantenimiento-api-auth-dev
    hostname: api.dev.local
    depends_on:
      - db
    image: solicitudes-mantenimiento-api-auth-dev
    volumes:
      - ./apps:/home/solicitudes-mantenimiento-api/apps
    ports:
      - 8082:8082
      - 10001:10001
    mem_limit: 768m
    cpu_percent: 60

  db:
    container_name: solicitudes-mantenimiento-api-db-dev
    hostname: db.dev.local
    image: mysql:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dev-db
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-password
    volumes:
      - ./mysql-dev/db:/var/lib/mysql
      - ./mysql-dev/dmp:/var/lib/mydmp
      - ./mysql-dev/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
