version: "2.2"

services:
  db:
    image: mysql:5.7.25
    container_name: spring-boot-seed-db-test
    hostname: db.test.local
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test-db
      - MYSQL_USER=test-user
      - MYSQL_PASSWORD=test-password
    volumes:
      - ./mysql-test/db:/var/lib/mysql
      - ./mysql-test/dmp:/var/lib/mydmp
      - ./mysql-test/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306