version: "2.2"

services:
  auth:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_auth_prod
    container_name: app-name-api-auth-prod
    hostname: api.prod.local
    depends_on:
      - db
      - gateway
    image: app-name-api-auth-prod
    volumes:
      - ./apps:/home/app-name-api/apps
    ports:
      - 8082:8082
    mem_limit: 768m
    cpu_percent: 60

  gateway:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_gateway_prod
    container_name: app-name-api-gateway-prod
    hostname: api.prod.local
    depends_on:
      - eureka
    image: app-name-api-gateway-prod
    volumes:
      - ./apps:/home/app-name-api/apps
    ports:
      - 8080:8080
    mem_limit: 768m
    cpu_percent: 60

  eureka:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_eureka_prod
    container_name: app-name-api-eureka-prod
    hostname: api.prod.local
    image: app-name-api-aureka-prod
    volumes:
      - ./apps:/home/app-name-api/apps
    ports:
      - 8081:8081
    mem_limit: 768m
    cpu_percent: 60

  db:
    container_name: app-name-api-db-prod
    hostname: db.prod.local
    image: mysql:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=prod-db
      - MYSQL_USER=prod-user
      - MYSQL_PASSWORD=prod-password
    volumes:
      - ./mysql-prod/db:/var/lib/mysql
      - ./mysql-prod/dmp:/var/lib/mydmp
      - ./mysql-prod/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306