version: "2.2"

services:
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_prod
    container_name: spring-boot-seed-prod
    hostname: api.prod.local
    depends_on:
      - db
    image: spring-boot-seed/prod
    volumes:
      - ./api:/home/spring-boot-seed/api
    networks:
      - prod-network
    ports:
      - ${API_PORT}:8080
      - 10001:10001
    mem_limit: 768m
    cpu_percent: 60

  db:
    image: mysql:5.7.23
    container_name: spring-boot-seed-db-prod
    hostname: db.prod.local
    environment:
      - MYSQL_DATABASE=prod-db
      - MYSQL_USER=prod-user
      - MYSQL_PASSWORD=prod-password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root-password
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/dmp:/var/lib/mydmp
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    networks:
      - prod-network

networks:
  prod-network: {}
