FROM openjdk:8-jdk

WORKDIR /home/spring-boot-seed

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y gettext-base maven && \
    apt-get clean && \
    apt-get autoremove

# Needed volume for embebed Spring Boot Tomcat.
VOLUME /tmp

COPY apps ./apps/

RUN cd apps && \
    mvn clean install -Dspring.profiles.active=dev -DskipTests=true --batch-mode --errors --debug && \
    mv ./core/target/core*.jar /app.jar

# Fix DNS resolution issues when nss is not installed
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENV JAVA_OPTS="-XX:+UseG1GC \
	-d64 \
	-server"

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=dev -jar /app.jar" ]