FROM openjdk:8-jdk

WORKDIR /home/spring-boot-seed

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y gettext-base maven && \
    apt-get clean && \
    apt-get autoremove

# Needed volume for embebed Spring Boot Tomcat.
VOLUME /tmp

COPY api ./api/

RUN cd api && \
    mvn clean install -Dspring.profiles.active=prod --batch-mode --errors --debug && \
    mv ./admin/target/app*.jar /app.jar

ENV JAVA_OPTS="-XX:+UseG1GC \
	-d64 \
	-server"

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=prod -jar /app.jar" ]